/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c8c6c5",
        "primary-fixed-dim": "#ffb787",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f5f4ef",
        "error": "#ba1a1a",
        "on-background": "#1b1c19",
        "tertiary-container": "#877158",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-container": "#656464",
        "on-tertiary-container": "#fffbff",
        "surface-variant": "#e4e2de",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb787",
        "secondary-container": "#e4e2e1",
        "surface-tint": "#964900",
        "on-surface-variant": "#574336",
        "surface": "#fbf9f4",
        "secondary-fixed": "#e4e2e1",
        "on-primary-fixed": "#311300",
        "secondary": "#5f5e5e",
        "on-primary-fixed-variant": "#723600",
        "outline": "#8a7264",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#30312e",
        "surface-container": "#efeee9",
        "outline-variant": "#dec1b0",
        "inverse-on-surface": "#f2f1ec",
        "on-primary": "#ffffff",
        "primary": "#E07000",
        "primary-deep": "#924700",
        "background": "#fbf9f4",
        "tertiary": "#6d5841",
        "surface-bright": "#fbf9f4",
        "on-surface": "#1b1c19",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#271907",
        "surface-container-high": "#e9e8e3",
        "surface-container-highest": "#e4e2de",
        "primary-fixed": "#ffdcc7",
        "error-container": "#ffdad6",
        "primary-container": "#b85b00",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ddc2a5",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#fadec0",
        "on-tertiary-fixed-variant": "#56432e",
        "surface-dim": "#dbdad5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-lg": "2rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "space-xl": "2rem",
        "gutter-sm": "1rem",
        "margin-lg": "3rem",
        "margin-sm": "1rem",
        "space-2xs": "0.125rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "margin": "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "headline-md": ["'Work Sans'", "sans-serif"],
        "headline-sm": ["'Work Sans'", "sans-serif"],
        "label-sm": ["'Work Sans'", "sans-serif"],
        "headline-lg": ["'Work Sans'", "sans-serif"],
        "title-lg": ["'Work Sans'", "sans-serif"],
        "body-sm": ["'Work Sans'", "sans-serif"],
        "body-md": ["'Work Sans'", "sans-serif"],
        "numeric-metric": ["'Work Sans'", "sans-serif"],
        "display-hero": ["'Work Sans'", "sans-serif"],
        "body-lg": ["'Work Sans'", "sans-serif"],
        "label-caps": ["'Work Sans'", "sans-serif"],
        "display-hero-mobile": ["'Work Sans'", "sans-serif"],
        sans: ["'Work Sans'", "'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeric-metric": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
};
